version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - PORT=3001
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DB=stocksync
      - MYSQL_PORT=3306
      - ADMIN_USER=testUsername
      - ADMIN_PASSWORD=123456
      - ADMIN_EMAIL=testEmail@email.com
      - JWT_SECRET=secret
      - SALT_ROUNDS=10
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    environment:
      - PORT=8080
    depends_on:
      - backend

  mysql:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: stocksync
    ports:
      - "3306:3306"
